/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvFileSource;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;

class AppTest {
    @Test
    @DisplayName("输入错误")
    void testInputError() {
        App app = new App();
        String result = app.TriangleJudge(1, 2, 101);
        assertEquals("输入错误", result);
    }

    @Test
    @DisplayName("非三角形")
    void testNotATriangle() {
        App app = new App();
        String result = app.TriangleJudge(1, 2, 3);
        assertEquals("非三角形", result);
    }

    @Test
    @DisplayName("等腰三角形")
    void testIsoscelesTriangle() {
        App app = new App();
        String result = app.TriangleJudge(3, 3, 5);
        assertEquals("等腰三角形", result);
    }

    @DisplayName(value = "三角形等价类测试用例")
    @ParameterizedTest
    @CsvFileSource(resources = "/三角形等价类测试用例.csv", numLinesToSkip = 1, encoding = "UTF-8")
    void fileTest0(int m, int a, int b, int c, String expected) {
        App app = new App();
        String result = app.TriangleJudge(a, b, c);
        assertEquals(expected, result);
    }

    @DisplayName(value = "三角形健壮性测试用例")
    @ParameterizedTest
    @CsvFileSource(resources = "/三角形健壮性测试用例.csv", numLinesToSkip = 1, encoding = "UTF-8")
    void fileTest1(int m, int a, int b, int c, String expected) {
        App app = new App();
        String result = app.TriangleJudge(a, b, c);
        assertEquals(expected, result);
    }

    @DisplayName(value = "三角形健壮性最坏状况测试用例")
    @ParameterizedTest
    @CsvFileSource(resources = "/三角形健壮性最坏状况测试用例.csv", numLinesToSkip = 1, encoding = "UTF-8")
    void fileTest2(int m, int a, int b, int c, String expected) {
        App app = new App();
        String result = app.TriangleJudge(a, b, c);
        assertEquals(expected, result);
    }

    @DisplayName(value = "三角形一般边界测试用例")
    @ParameterizedTest
    @CsvFileSource(resources = "/三角形一般边界测试用例.csv", numLinesToSkip = 1, encoding = "UTF-8")
    void fileTest3(int m, int a, int b, int c, String expected) {
        App app = new App();
        String result = app.TriangleJudge(a, b, c);
        assertEquals(expected, result);
    }

}
