/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvFileSource;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;

class AppTest {
    @DisplayName("一般边界值测试")
    @ParameterizedTest
    @CsvFileSource(resources = "/一般边界值测试.csv", numLinesToSkip = 1, encoding = "UTF-8")
    void fileTest0(String m, int a, int b, int c, String expected) {
        App app = new App();
        String result = app.TriangleJudge(a, b, c);
        assertEquals(expected, result);
    }

    @DisplayName("健壮性边界值测试")
    @ParameterizedTest
    @CsvFileSource(resources = "/健壮性边界值测试.csv", numLinesToSkip = 1, encoding = "UTF-8")
    void fileTest1(String m, int a, int b, int c, String expected) {
        App app = new App();
        String result = app.TriangleJudge(a, b, c);
        assertEquals(expected, result);
    }

    @DisplayName("最坏情况一般边界值测试")
    @ParameterizedTest
    @CsvFileSource(resources = "/最坏情况一般边界值测试.csv", numLinesToSkip = 1, encoding = "UTF-8")
    void fileTest2(String m, int a, int b, int c, String expected) {
        App app = new App();
        String result = app.TriangleJudge(a, b, c);
        assertEquals(expected, result);
    }

    @DisplayName("最坏情况健壮性边界值测试")
    @ParameterizedTest
    @CsvFileSource(resources = "/最坏情况健壮性边界值测试.csv", numLinesToSkip = 1, encoding = "UTF-8")
    void fileTest3(String m, int a, int b, int c, String expected) {
        App app = new App();
        String result = app.TriangleJudge(a, b, c);
        assertEquals(expected, result);
    }
}
