/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example4;

public final class YesterDate {
    // 常量定义
    private static final int LEAP_YEAR_DIVISOR_4 = 4;
    private static final int LEAP_YEAR_DIVISOR_100 = 100;
    private static final int LEAP_YEAR_DIVISOR_400 = 400;
    private static final int DAYS_IN_MONTH_31 = 31;
    private static final int DAYS_IN_MONTH_30 = 30;
    private static final int DAYS_IN_MONTH_FEBRUARY_LEAP = 29;
    private static final int DAYS_IN_MONTH_FEBRUARY_NON_LEAP = 28;
    private static final int MONTH_JANUARY = 1;
    private static final int MONTH_MARCH = 3;
    private static final int MONTH_APRIL = 4;
    private static final int MONTH_MAY = 5;
    private static final int MONTH_JUNE = 6;
    private static final int MONTH_JULY = 7;
    private static final int MONTH_AUGUST = 8;
    private static final int MONTH_SEPTEMBER = 9;
    private static final int MONTH_OCTOBER = 10;
    private static final int MONTH_NOVEMBER = 11;
    private static final int MONTH_DECEMBER = 12;
    private static final int MIN_YEAR = 1950;
    private static final int MAX_YEAR = 2050;
    private static final int MIN_MONTH = 1;
    private static final int MAX_MONTH = 12;
    private static final int MIN_DAY = 1;
    private static final int SPECIAL_YEAR = 1950;
    private static final int SPECIAL_MONTH = 1;
    private static final int SPECIAL_DAY = 1;
    private static final int DAY_THRESHOLD = 2;

    // 隐藏构造器，工具类不应被实例化
    private YesterDate() {
    }

    // 判断是否为闰年
    public static boolean isLeapYear(final int year) {
        return year % LEAP_YEAR_DIVISOR_4 == 0 && year % LEAP_YEAR_DIVISOR_100 != 0
                || year % LEAP_YEAR_DIVISOR_400 == 0;
    }

    // 判断指定月份的天数
    public static int getDayOfMonth(final int year, final int month) {
        return switch (month) {
            case MONTH_JANUARY, MONTH_MARCH, MONTH_MAY, MONTH_JULY, MONTH_AUGUST, MONTH_OCTOBER, MONTH_DECEMBER ->
                DAYS_IN_MONTH_31;
            case MONTH_APRIL, MONTH_JUNE, MONTH_SEPTEMBER, MONTH_NOVEMBER -> DAYS_IN_MONTH_30;
            default -> isLeapYear(year) ? DAYS_IN_MONTH_FEBRUARY_LEAP : DAYS_IN_MONTH_FEBRUARY_NON_LEAP;
        };
    }

    // 判断是否为有效日期
    public static boolean isValidDate(final int year, final int month, final int day) {
        if (year < MIN_YEAR || year > MAX_YEAR) {
            return false;
        }
        if (month < MIN_MONTH || month > MAX_MONTH) {
            return false;
        }
        if (day < MIN_DAY || day > getDayOfMonth(year, month)) {
            return false;
        }
        return true;
    }

    // 计算指定日期的前一天
    public static String getYesterDay(final int year, final int month, final int day) {
        // 判断输入的日期信息是否合法
        if (!isValidDate(year, month, day)) {
            return "Invalid date";
        }
        // 特殊情况：1950年1月1日返回Invalid date
        if (day == SPECIAL_DAY && month == SPECIAL_MONTH && year == SPECIAL_YEAR) {
            return "Invalid date";
        }
        if (day >= DAY_THRESHOLD) {
            return String.format("%d-%02d-%02d", year, month, day - 1);
        }
        if (month == MONTH_JANUARY) {
            return String.format("%d-%02d-%02d", year - 1, MONTH_DECEMBER, DAYS_IN_MONTH_31);
        }
        return String.format("%d-%02d-%02d", year, month - 1, getDayOfMonth(year, month - 1));
    }
}
