/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example5;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LinkedListRemoveTest {

    // 按对象删除元素->null,test1,test3,null
    @Test
    void remove_Object_All() {
        LinkedListRemove<String> list = new LinkedListRemove<>();
        list.add("test1");
        list.add("test2");
        list.add(null);
        assertTrue(list.remove(null));
        assertTrue(list.remove("test1"));
        assertFalse(list.remove("test3"));
        assertFalse(list.remove(null));
    }

}
