/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example;

import java.util.Scanner;

public class App {
    public String TriangleJudge(int a, int b, int c) {
        if (a < 1 || a > 100 || b < 1 || b > 100 || c < 1 || c > 100)
            return "输入错误";
        if (a + b <= c || a + c <= b || b + c <= a)
            return "非三角形";
        else if (a == b && a == c)
            return "等边三角形";
        else if (a != b && a != c && b != c)
            return "一般三角形";
        else
            return "等腰三角形";
    }

    public static void main(String[] args) {
        int a, b, c;
        Scanner sc = new Scanner(System.in);
        System.out.println("请输入第一条边：");
        a = sc.nextInt();
        System.out.println("请输入第二条边：");
        b = sc.nextInt();
        System.out.println("请输入第三条边：");
        c = sc.nextInt();
        System.out.println(new App().TriangleJudge(a, b, c));
    }
}
