/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example3;

import org.junit.jupiter.api.Test;
import java.time.ZonedDateTime;
import java.time.ZoneId;
import static org.junit.jupiter.api.Assertions.*;

class PhoneBillCalculatorTest {
    private final PhoneBillCalculator calculator = new PhoneBillCalculator();
    private final ZoneId ZONE = ZoneId.of("America/New_York");

    // 测试小于一分钟的通话费用
    @Test
    void testLessThanOneMinute() {
        Call call = new Call(ZonedDateTime.now(ZONE), ZonedDateTime.now(ZONE).plusSeconds(30));
        assertEquals(0.05, calculator.calculateFee(call));
    }

    // 测试20分钟的通话费用
    @Test
    void testTwentyMinutes() {
        Call call = new Call(ZonedDateTime.now(ZONE), ZonedDateTime.now(ZONE).plusMinutes(20));
        assertEquals(1, calculator.calculateFee(call));
    }

    // 测试大于20分钟的通话费用
    @Test
    void testMoreThanTwentyMinutes() {
        Call call = new Call(ZonedDateTime.now(ZONE), ZonedDateTime.now(ZONE).plusMinutes(21));
        assertEquals(1.1, calculator.calculateFee(call));
    }

    // 夏令时特殊场景测试
    @Test
    void testSummerTime() {
        // 测试夏令时开始前的通话
        ZonedDateTime start = ZonedDateTime.of(2026, 3, 8, 1, 0, 0, 0, ZONE);
        ZonedDateTime end = ZonedDateTime.of(2026, 3, 8, 3, 0, 0, 0, ZONE);
        Call call = new Call(start, end);
        // 实际通话时间为60分钟
        assertEquals(60, calculator.calculateCallMinutes(call));
    }

    // 测试通话时间为0
    @Test
    void testZeroTime() {
        ZonedDateTime start = ZonedDateTime.now(ZONE);
        ZonedDateTime end = start;
        Call call = new Call(start, end);
        assertThrows(IllegalArgumentException.class, () -> calculator.calculateFee(call));
    }

    // 通话时长大于30小时
    @Test
    void testLongCall() {
        Call call = new Call(ZonedDateTime.now(ZONE), ZonedDateTime.now(ZONE).plusHours(30));
        assertThrows(IllegalArgumentException.class, () -> calculator.calculateFee(call));
    }

    // 开始时间在结束时间之后
    @Test
    void testStartAfterEnd() {
        Call call = new Call(ZonedDateTime.now(ZONE), ZonedDateTime.now(ZONE).minusMinutes(1));
        assertThrows(IllegalArgumentException.class, () -> calculator.calculateFee(call));
    }
}
