/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example3;

import java.time.Duration;
import java.time.ZonedDateTime;

public class PhoneBillCalculator {
    // 小于20分钟的分钟通话费用
    private static final double RATE_UNDER_20 = 0.05;
    // 超过20分钟的分钟通话费用
    private static final double RATE_OVER_20 = 0.1;
    // 最大通话时间
    private static final double MAX_CALL_MINUTES = 1800;
    // 阈值
    private static final double THRESHOLD = 20;
    // 每分钟秒数
    private static final int SECONDS_PER_MINUTE = 60;

    // 计算通话费用
    public double calculateFee(final Call call) {
        validateCall(call);
        int minutes = calculateCallMinutes(call);
        return calculateByMinutes(minutes);
    }

    // 校验通话记录有效性
    private void validateCall(final Call call) {
        ZonedDateTime startT = call.getStartTime();
        ZonedDateTime endT = call.getEndTime();
        if (startT.isAfter(endT)) {
            throw new IllegalArgumentException("开始时间不能晚于结束时间");
        }
        long seconds = Duration.between(startT, endT).getSeconds();
        if (seconds >= MAX_CALL_MINUTES * SECONDS_PER_MINUTE) {
            throw new IllegalArgumentException("通话时长不能超过30小时");
        }
    }

    // 计算通话时长(ZonedDateTime可以自动处理夏令时)
    public int calculateCallMinutes(final Call call) {
        Duration duration = Duration.between(call.getStartTime(), call.getEndTime());
        long seconds = duration.getSeconds();
        return (int) Math.ceil((double) seconds / SECONDS_PER_MINUTE);
    }

    // 通话费用(根据分钟数计算)
    public double calculateByMinutes(final int minutes) {
        if (minutes <= 0) {
            throw new IllegalArgumentException("通话时长必须大于0分钟");
        }
        if (minutes <= THRESHOLD) {
            return minutes * RATE_UNDER_20;
        } else {
            return RATE_UNDER_20 * THRESHOLD + (minutes - THRESHOLD) * RATE_OVER_20;
        }
    }
}
