/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example5;

public class LinkedListRemove<E> {

    // 双向链表节点
    private static class Node<E> {
        E item;
        Node<E> next;
        Node<E> prev;

        Node(Node<E> prev, E element, Node<E> next) {
            this.item = element;
            this.next = next;
            this.prev = prev;
        }
    }

    // 链表首尾节点 + 长度
    private Node<E> first;
    private Node<E> last;
    private int size;

    // ---------------- 辅助方法：添加元素（测试用） ----------------
    public void add(E e) {
        linkLast(e);
    }

    private void linkLast(E e) {
        final Node<E> l = last;
        final Node<E> newNode = new Node<>(l, e, null);
        last = newNode;
        if (l == null)
            first = newNode;
        else
            l.next = newNode;
        size++;
    }

    public int size() {
        return size;
    }

    public boolean isEmpty() {
        return size == 0;
    }

    // ===================== 1. 无参remove()：删除第一个元素 =====================
    public E remove() {
        if (size == 0)
            throw new java.util.NoSuchElementException();
        return unlinkFirst(first);
    }

    private E unlinkFirst(Node<E> f) {
        final E element = f.item;
        final Node<E> next = f.next;
        f.item = null;
        f.next = null;
        first = next;
        if (next == null)
            last = null;
        else
            next.prev = null;
        size--;
        return element;
    }

    // ===================== 2. 按索引remove(int)：删除指定位置元素 =====================
    public E remove(int index) {
        checkIndex(index);
        return unlink(node(index));
    }

    private void checkIndex(int index) {
        if (index < 0 || index >= size)
            throw new IndexOutOfBoundsException();
    }

    Node<E> node(int index) {
        Node<E> x;
        if (index < (size >> 1)) {
            x = first;
            for (int i = 0; i < index; i++)
                x = x.next;
        } else {
            x = last;
            for (int i = size - 1; i > index; i--)
                x = x.prev;
        }
        return x;
    }

    E unlink(Node<E> x) {
        final E element = x.item;
        final Node<E> next = x.next;
        final Node<E> prev = x.prev;

        if (prev == null) {
            first = next;
        } else {
            prev.next = next;
            x.prev = null;
        }

        if (next == null) {
            last = prev;
        } else {
            next.prev = prev;
            x.next = null;
        }

        x.item = null;
        size--;
        return element;
    }

    // ===================== 3. 按对象remove(Object)：删除指定元素 =====================
    public boolean remove(Object o) {
        Node<E> x = first;
        if (o == null) {
            for (; x != null; x = x.next) {
                if (x.item == null) {
                    unlink(x);
                    return true;
                }
            }
        } else {
            for (; x != null; x = x.next) {
                if (o.equals(x.item)) {
                    unlink(x);
                    return true;
                }
            }
        }
        return false;
    }

}
